version: "3"
services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - simple-test
    volumes:
      - redis-data:/data
    expose:
      - 6379
  front:
    build: ./frontend/.
    ports:
      - "4200:80"
    networks:
      - simple-test
  back:
    build: ./backend/.
    ports:
      - "3000:3000"
    networks:
      - simple-test
networks:
  simple-test:
volumes:
  redis-data:
